server {
    listen 80;
    server_name localhost;

    # Redirection des appels API vers le conteneur Python
    location /api {
        proxy_pass http://localhost:3000; # 'localhost' car ils seront dans la même instance
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Optionnel : Gestion des erreurs
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}