version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: flowsign_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: flowsign_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flowsign
    depends_on:
      - mongodb

  proxy:
  image: nginx:alpine
  container_name: flowsign_proxy
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./frontend:/usr/share/nginx/html   # ← ajoute cette ligne
  depends_on:
    - backend

volumes:
  mongo_data: