version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: flowsign_db
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: flowsign_api
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend/static/animations:/app/static/animations
    depends_on:
      - mongodb

  proxy:
    image: nginx:alpine
    container_name: flowsign_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs  # certificat auto-signé monté ici
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mongo_data: